#!/usr/bin/expect
#
# edn test
#
# Usage:
#   ./edn_test.exp board_type
#
# Example:
#   ./edn_test.exp BF537-STAMP
#

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
source ../common/kernel_boot.exp

step "Start testing"
set case_num 0
set timeout 5
expect -re $kernel_prompt

set timeout 1800
incr case_num
send "time edn\r"
while 1 {
    expect {
        -re "Hardware Trace" {
            expect -re $kernel_prompt
            case_fail $case_num
        }
        -re "cycles per loop.*jpegdct.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_user "edn test timeout\n"
            set timeout 180
            send "\3\r"
            expect -re $kernel_prompt
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
