#!/usr/bin/expect
#
# This is test program of serial driver.
#
# Usage:
#   ./serial_test.exp board_type
#
# Example:
#   ./serial_test.exp beagle
#


source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

set target_tty /dev/$def_uart_port
set target_file aaa
set host_file bbb
set save_file ccc

step "Start kermit"
source ../common/spawn_kermit.exp

step "Update kernel image"
source ../common/update_image.exp

step "Start testing"
set target_id $spawn_id
set ttyflags "-icrnl -ixon igncr -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoke -hupcl -echoctl -parenb -parodd cs8 hupcl -cstopb cread clocal -crtscts min 1 time 0"

set case_num 0

send -s "stty -echo;cat\r"
set timeout 3
while 1 {
    expect {
        -re "# " {
            case_fail $case_num
        }
        timeout {
            break
        }
    }
}

set timeout 3
set this_case FAIL
spawn /bin/bash
while 1 {
    expect {
        -re $sh_prompt {
            break
        }
        timeout {
            send_user "No prompt!\n"
            break
        }
    }
}

set timeout 20
incr case_num
set host_id $spawn_id

for {set i 0} {$i<500} {incr i} {
    send "1"
    expect {
        "1" {
        }
        timeout {
            send_user "Fail to receive single byte in a long loop!\n"
            case_fail $case_num
        }
    }
}
send "\n"
expect {
    -re $sh_prompt {
        send_user "Succeed to receive single byte in a long loop!\n"
        case_pass $case_num
    }
    timeout {
        send_user "No prompt after receive single byte in a long loop!\n"
        case_fail $case_num
    }
}

incr case_num
for {set i 0} {$i<30} {incr i} {

    set spawn_id $host_id
    send  "echo $STRDATA > $ttydev \r"
    while 1 {
        expect {
            -re $sh_prompt {
                break
            }
            timeout {
                send_user "No prompt!\n"
                break
            }
        }
    }

    set spawn_id $target_id
    while 1 {
        expect {
            "$STRDATA" {
                set this_case PASS
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }
}

if { $this_case == "PASS" } {
    case_pass $case_num
} else {
    case_fail $case_num
}

send -s "\3"
expect -re $kernel_prompt

incr case_num
set this_case FAIL

send "stty echo\r"
expect -re $kernel_prompt

set timeout 3
send "\r"
while 1 {
    expect {
        -re $kernel_prompt {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

for {set i 0} {$i<30} {incr i} {
    send  "$STRDATA\r"
    while 1 {
        expect {
            "$STRDATA" {
                set this_case PASS
                break
            }
            timeout {
                case_fail $case_num
            }
        }
    }
}

if { $this_case == "PASS" } {
    case_pass $case_num
} else {
    case_fail $case_num
}


incr case_num
while 1 {
    set timeout 5
    send -s "ls\n"
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
while 1 {
    set timeout 5
    send -s "dmesg\n"
    send -s "dmesg\n"
    send -s "dmesg\n"
    send -s "cat /proc/slabinfo\n"
    expect {
        "slabinfo - version" { break }
        timeout {
            case_fail $case_num
        }
    }
}

while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
while 1 {
    set timeout 5
    send -s "cat /proc/kallsyms\n"
    expect {
        "start" {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

while 1 {
    sleep 1
    send -s "\3"
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}


incr case_num
set timeout 30
for {set i 0} {$i<100} {incr i} {
    send "$STRDATA\n"
}
send -s "====================================\n"

while 1 {
    expect {
        -re "=========\[']?: \[Nn]o" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
while 1 {
    set timeout 5
    send -s "vi\n"
    expect {
        -re  "1.*1" {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

while 1 {
    set timeout 60
    send -s "i"
    send -s "adskf\n"
    send -s "werigji\n"
    send -s "werigji\n"
    send -s "werigji\n"
    send -s "werigji\n"
    send -s "werigji\n"
    send -s "werigji\n"
    for {set i 0} {$i<100} {incr i} {
        send -s "x"
        expect {
            "x" {
            }
            timeout {
                case_fail $case_num
            }
        }
    }

    send -s "a\n"
    send -s "b\n"
    send -s "c\n"
    send -s "d\n"
    send -s "e\n"
    send -s "f\n"
    send -s "\n"
    send -s "$STRDATA"
    send -s "$STRDATA"
    send -s "$STRDATA"
    send -s "$STRDATA\n"
    for {set i 0} {$i<100} {incr i} {
        send "$STRDATA\n"
    }
    send -s "===================================#"
    expect {
        "#" {
            sleep 2
            send -s "\033"
            sleep 2
            send -s ":q!\n"
            sleep 2
            send -s "\n"
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send_user "\n #######################################################################################################\n"
step "Reboot the kernel."
set boot_image uImage
append bootargs_param6 " console=null"
set bootargs             $bootargs_param6
source ../common/reboot_kernel.exp

set timeout 10
incr case_num
send "ifconfig $eth_dev $targetip\r"
while 1 {
    expect {
        -re "$eth_dev: link up" {
            sleep 2
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s "\x81"
send -s "c"
while 1 {
    expect {
        "ermit>" {
            set back_flag SUCCESS
            break
        }
        timeout {
            send_user "ERROR: back to kermit error\n"
            break
        }
    }
}

send -s "q\r"
while 1 {
    expect {
        "Closing *OK" {
            set close_flag SUCCESS
            break
        }
        timeout {
            send_user "Close kermit error.\n"
            break
        }
    }
}

set timeout 3
sleep 3
spawn /bin/bash
set telnet_id $spawn_id
expect  -re  $sh_prompt

### This case is sending file from  host to target.
incr case_num
send -s "telnet $targetip\r"
while 1 {
    expect {
        -re $kernel_prompt { break }
        timeout {
            send_user "Failed inital telnet\n"
            case_fail $case_num
        }
    }
}

incr case_num
send -s "cat /proc/kallsyms > $save_file \r"
while 1 {
    expect {
        -re $kernel_prompt { break }
        timeout {
            send_user "Failed to save file.\n"
            case_fail $case_num
        }
    }
}

incr case_num
send -s "stty -F $target_tty ispeed $baud_rate ospeed $baud_rate $ttyflags\r"
while 1 {
    expect {
        -re $kernel_prompt { break }
        timeout {
            send_user "Failed to set uart speed.\n"
            case_fail $case_num
        }
    }
}

send -s "cat $target_tty > $target_file\r"
while 1 {
    expect {
        -re $kernel_prompt { break }
        timeout { break }
    }
}


spawn /bin/bash
set host_sh_id $spawn_id
expect  -re  $sh_prompt

send -s "rcp root@$targetip:/$save_file . \r"
while 1 {
    expect {
        -re  $sh_prompt { break }
        timeout {
            send_user "Failed to rcp $target_file to host.\n"
            case_fail $case_num
        }
    }
}

while 1 {
    send -s "stty -F $ttydev ispeed $baud_rate ospeed $baud_rate $ttyflags\r"
    expect {
        -re $sh_prompt { break }
        timeout {
            puts " set $ttydev failed...\n"
            break
        }
    }
}

set timeout 60
while 1 {
    send -s " cat $save_file > $ttydev  \r"
    expect {
        -re $sh_prompt { break }
        timeout {
            puts "send data failed...\n"
            break
        }
    }
}

set spawn_id $telnet_id

sleep 3
while 1 {
    expect {
        -re $kernel_prompt {
            puts "Fail to wait.\n"
            break
        }
        timeout {
            puts "\nStill wait.\n"
            break
        }
    }
}

send "\3"
while 1 {
    expect {
        -re "$kernel_prompt" {
            send_log "Catted file is got on target.\n"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 60
send -s "diff -u $save_file $target_file \r"
while 1 {
    expect {
        -re "\\\+\\\+\\\+" {
            expect -re  "$kernel_prompt"
            send_log "\nTwo files diffs.\n "
            case_fail $case_num
            break
        }
        "differ" {
            send_log "Two files diffs!\n"
            case_fail $case_num
            break
        }
        timeout {
            expect -re  "$kernel_prompt"
            send_log "Success case.\n"
            case_pass $case_num
            break
        }
    }
}

######################################################################
### This case is sending file from  target to host.

incr case_num
set spawn_id $telnet_id
send -s "stty -F $target_tty ispeed $baud_rate ospeed $baud_rate $ttyflags\r"
while 1 {
    expect {
        -re $kernel_prompt { break }
        timeout {
            send_user "Failed to set uart speed.\n"
            case_fail $case_num
        }
    }
}
set spawn_id $host_sh_id

sleep 3
send "ls\r"
expect -re $sh_prompt

send -s "stty -F $ttydev ispeed $baud_rate ospeed $baud_rate $ttyflags\r"
while 1 {
    expect {
        -re $sh_prompt { break }
        timeout {
            send_user "Failed to set uart speed.\n"
            case_fail $case_num
        }
    }
}

sleep 3
send "ls\r"
expect -re "$sh_prompt"
while 1 {
    send -s "cat $ttydev > $host_file \r"
    expect {
        -re "$sh_prompt" {
            puts "Fail to cat on host.\n"
            break
        }
        timeout {
            puts "wait for receiving data...\n"
            break
        }
    }
}

set spawn_id $telnet_id
set timeout 60
while 1 {
    send -s "cat $save_file > $target_tty\r"
    expect {
        -re "$kernel_prompt" { break }
        timeout {
            send_user "Failed inital telnet\n"
            case_fail $case_num
        }
    }
}

set spawn_id $host_sh_id
sleep 3
set timeout 5
while 1 {
    expect {
        -re "$sh_prompt" {
            puts "Fail to wait.\n"
            break
        }
        timeout {
            puts "\nStill wait.\n"
            break
        }
    }
}

send -s "\3"
while 1 {
    expect {
        -re "$sh_prompt" {
            send_log "Catted file is got on host.\n"
            break
        }
        timeout {
            puts "Failed to come out.\n"
            break
        }
    }
}

set timeout 60
send -s "diff -u $host_file $save_file \r"
while 1 {
    expect {
        -re "\\\+\\\+\\\+" {
            expect -re  "$sh_prompt"
            send_log "\nTwo files diffs. \n"
            case_fail $case_num
        }
        "differ" {
            send_log "Two files diffs!\n"
            case_fail $case_num
        }
        timeout {
            expect -re  "$sh_prompt"
            send_log "Success case.\n"
            case_pass $case_num
            break
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
