#!/usr/bin/expect
#
# debug mmrs test
#
# Usage:
#   ./debug_mmrs_test.exp board_type
#
# Example:
#   ./debug_mmrs_test.exp BF537-STAMP
#

source ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param1
source ../common/kernel_boot.exp


step "Start testing"
set case_num 0
set timeout 10

expect -re $kernel_prompt
send "\r"
expect -re $kernel_prompt

set timeout 360
incr case_num
send "find /sys/kernel/debug/blackfin/ -type f -print -exec cat \'{}\' \\;\r"
while 1 {
    expect {
        -re "Kernel OOPS|Kernel panic|Hardware Trace" {
            set timeout 20
            expect -re $kernel_prompt
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
