#!/usr/bin/expect

#
# This test case is to test the g729 lib in bfgdots
#
# Usage:
#   ./g729_test.exp board_type
#
# Example:
#   ./g729_test.exp BF537-STAMP
#

source ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
source ../common/kernel_boot.exp

step "test preparation"
set case_num 0
set timeout 10
set TEST_PROG "g729ab_test g729ab_testsimgot g729ab_testfdpic g729ab_testfdpic_so"

expect -re $kernel_prompt
send "mv /g729/* /var; cd /var\r"
expect -re $kernel_prompt

step "Start testing."
foreach element $TEST_PROG {
    global case_num

    incr case_num
    set timeout 20
    send "./alltests.sh $element\r"
    while 1 {
        expect {
            -re "(\[eE]rror|\[fF]ail|not found).*$kernel_prompt" {
                case_fail $case_num
            }
            -re "G729AB Decoder.*$kernel_prompt" {
                case_pass $case_num
                break
            }
            timeout {
                send -s "\3"
                send_log "timeout\n"
                case_fail $case_num
            }
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
