#!/usr/bin/expect
#
# lmbench performance test
#
# Usage:
#   ./lmbench_test.exp board_type
#
# Example:
#   ./lmbench_test.exp BF537-STAMP
#

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
source ../common/kernel_boot.exp

step "Start testing"
set case_num 0
set timeout 10
expect -re $kernel_prompt

set timeout 1500
incr case_num
send "time nbench\r"
while 1 {
    expect {
        -re "NUMERIC SORT +: +(\[0-9]+\.\[0-9e+]+) " {
            set numeric_sort $expect_out(1,string)
        }
        -re "BITFIELD +: +(\[0-9]+\.\[0-9e+]+) " {
            set bitfield  $expect_out(1,string)
        }
        -re "Trademarks.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
