#!/usr/bin/expect

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Spawn kermit"
source ../common/spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../common/reboot_kernel.exp

step "Update kernel image"
source ../common/update_image.exp

sleep 5
send "\r"
expect -re $kernel_prompt

set case_num 0
incr case_num

step "Start testing"
set timeout 20
send "cd /; ls\r"
while 1 {
    expect {
        -re "home.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_user "timeout\n"
            case_fail $case_num
            break
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
