#!/usr/bin/expect

source  ../common/kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../common/spawn_kermit.exp

step "Reboot the kernel."
source ../common/reboot_kernel.exp 

step "Start testing."

set timeout 5

set case_num 0
incr case_num

set timeout 500

send -s  "dmesg\r" 
while 1 {
   expect {

       -re "text\[\x20\t]+=\[\x20\t]+(0x\[0-9a-fA-F]+)-(0x\[0-9a-fA-F]+)\[\r\n]" {
            set map_text $expect_out(1,string)
                case_pass $case_num
                break
         }

      timeout {
                case_fail $case_num
	exit
         }
     }
}

incr case_num
send_user "\nmap_text  $map_text\n"
send_user "\nCheck if map_text is the right value\n"
if {$map_text == 0x00002000 } {
   case_pass $case_num
} else {
   case_fail $case_num
}

all_pass
send_user "Ending $argv0\n"
log_file
