#!/usr/bin/expect
#
# Test script for sdio interface wifi test.
#
# Usage:
#   ./sdio_wifi_test.exp  board_type  essid  ping_ipaddr
#
# Example:
#   ./sdio_wifi_test.exp  BF5548-EZKIT linksys 1234567890 192.168.1.1
#

source ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

if { $argc < 3} {
   puts "Usage:  $argv0  board_type  essid  key  ping_ipaddr"
   puts ""
   exit
}
set essid [lindex $argv 1]
set key   [lindex $argv 2]
set ping_ipaddr [lindex $argv 3]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
# Different bootargs can be set here.
# For example:
# set bootargs $bootargs_param1
source ../common/kernel_boot.exp

step "Start testing"
set case_num 0
sleep 10

incr case_num
set timeout 5
send "dmesg|grep mmc\r"
while 1 {
    expect {
        -re "SDIO card at address.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_user "FAIL: detect sdio wifi card\n"
            case_fail $case_num
        }
    }
}

step "Load Module libertas"
incr case_num
set timeout 20
send "modprobe libertas_sdio\r"
while 1 {
    expect {
        -re "Libertas SDIO driver.*Marvell WLAN 802\.11 adapter" {
            case_pass $case_num
            break
        }
        timeout {
            send_user "FAIL: install wifi firmware\n"
            case_fail $case_num
        }
    }
}

expect -re $kernel_prompt

step "Setup wifi configuration"
incr case_num
set timeout 5
send "ifconfig wlan0 up\r"
while 1 {
   expect {
       -re $kernel_prompt {
         case_pass $case_num
         break
      }
      timeout {
         send_user "\ntimeout: wlan0 up\n"
         case_fail $case_num
      }
   }
}

incr case_num
set timeout 5
send "ifconfig\r"
while 1 {
   expect {
       -re "wlan0.*$kernel_prompt" {
         case_pass $case_num
         break
      }
      timeout {
         send_user "\ntimeout: wlan0 up\n"
         case_fail $case_num
      }
   }
}

incr case_num
set timeout 5
send "iwlist wlan0 scan\r"
while 1 {
   expect {
       -re "$essid" {
         expect -re $kernel_prompt
         case_pass $case_num
         break
      }
      timeout {
         send_user "\ntimeout: wlan scan\n"
         case_fail $case_num
      }
   }
}

incr case_num
set timeout 5
send "iwconfig wlan0 essid $essid key $key\r"
while 1 {
   expect {
       -re $kernel_prompt {
         case_pass $case_num
         break
      }
      timeout {
         send_user "\ntimeout: wifi config\n"
         case_fail $case_num
      }
   }
}

incr case_num
set timeout 5
send "iwconfig wlan0\r"
while 1 {
   expect {
       -re "ESSID:\"$essid\".*$kernel_prompt" {
         case_pass $case_num
         break
      }
      timeout {
         send_user "\nCan not find $essid\n"
         case_fail $case_num
      }
   }
}

incr case_num
set timeout 5
send "udhcpc -i wlan0 &\r"
while 1 {
   expect {
       -re "udhcpc -i wlan0\r\n$kernel_prompt" {
         case_pass $case_num
         break
      }
      timeout {
         send_user "\ntimeout: get wlan ip\n"
         case_fail $case_num
      }
   }
}

sleep 5

incr case_num
set timeout 5
send "ifconfig wlan0\r"
while 1 {
   expect {
       -re "inet addr:(\[0-9]+\.)+.*$kernel_prompt" {
         case_pass $case_num
         break
      }
      timeout {
         send_user "\nCan not get ip\n"
         case_fail $case_num
      }
   }
}

step "ping to target"
incr case_num
set timeout 60
send "ping -c 50 $ping_ipaddr\r"
while 1 {
   expect {
      -re ".* 0% packet loss.*$kernel_prompt" {
         send_user "\nping remote host: pass\n"
         case_pass $case_num
         break
      }
      timeout {
         send_user "\nping fail\n"
         case_fail $case_num
      }
   }
}

all_pass
send_user "Ending $argv0\n"
log_file
