#!/usr/bin/expect
#
# Test ethernet driver with tool netperf;
#
# Usage:
#   ./ethernet_test.exp board_type
#
# Example:
#   ./ethernet_test.exp beagle
#

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Update kernel image"
source ../common/update_image.exp

step "Start testing"

set test_time 600
set TransRate  0
set Throughput  0

incr case_num
set timeout 5
send "ifconfig usb0\r"
while 1 {
    expect {
        -re "$targetip.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2000
send "netperf -H $serverip -t TCP_RR -l $test_time > netperf_tcp_rr\r"
while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_user "Fail: ethernet TCP_RR test\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2000
send "netperf -H $serverip -t TCP_STREAM -l $test_time  > netperf_tcp_stream\r"
while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_user "Fail: ethernet TCP_STREAM test\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "cat netperf_tcp_rr\r"
while 1 {
    expect {
        -re "$test_time\\\.\[0-9]{2} +(\[0-9]+\\\.\[0-9]{2})" {
            set TransRate $expect_out(1,string)
            expect -re $kernel_prompt
            send_log "TransRate $expect_out(1,string)\n"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "cat netperf_tcp_stream\r"
while 1 {
    expect {
        -re "$test_time\\\.\[0-9]{2} +(\[0-9]+\\\.\[0-9]{2})" {
            set Throughput $expect_out(1,string)
            expect -re $kernel_prompt
            send_log "Throughput $expect_out(1,string)\n"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send_user "Evaluate performance result.\n"
if { $TransRate > 2000 && $Throughput > 50 } {
    case_pass $case_num
} else {
    case_fail $case_num
}

all_pass
send_user "Ending $argv0\n"
log_file
