#!/usr/bin/expect
#
# Test ethernet driver with tool netperf;
#
# Usage:
#   1. Test normal ethernet:
#      ./ethernet_test.exp board_type
#   2. Test through USB-ethernet converter:
#      ./ethernet_test.exp board_type usb
#
# Example:
#   ./ethernet_test.exp beagle
#   ./ethernet_test.exp beagle usb
#

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Update kernel image"
source ../common/update_image.exp

if { [lindex $argv 1] == "usb" } {
    append TITLE " (USB)"
    set test_dev     $usb_eth_dev
    set non_test_dev $eth_dev
    set test_ip      "10.100.5.50"
    set test_server_ip "10.100.5.174"
} else {
    set test_dev     $eth_dev
    set non_test_dev $usb_eth_dev
    set test_ip      $targetip
    set test_server_ip $serverip
}
send_user "\n########## Test ethernet with $test_dev ##########\n"

step "Start testing"

set test_time  600
set TransRate  0
set Throughput 0

incr case_num
set timeout 5
send "ifconfig $test_dev $test_ip up\r"
while 1 {
    expect {
        -re "ifconfig:.*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "ifconfig $non_test_dev down\r"
while 1 {
    expect {
        -re "ifconfig:.*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "ifconfig\r"
while 1 {
    expect {
        -re "$non_test_dev.*$kernel_prompt" {
            case_fail $case_num
        }
        -re "$test_ip.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2000
send "netperf -H $test_server_ip -t TCP_RR -l $test_time > netperf_tcp_rr\r"
while 1 {
    expect {
        -re "netperf:.*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_user "Fail: ethernet TCP_RR test\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 2000
send "netperf -H $test_server_ip -t TCP_STREAM -l $test_time  > netperf_tcp_stream\r"
while 1 {
    expect {
        -re "netperf:.*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            send_user "Fail: ethernet TCP_STREAM test\n"
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "cat netperf_tcp_rr\r"
while 1 {
    expect {
        -re "$test_time\\\.\[0-9]{2} +(\[0-9]+\\\.\[0-9]{2})" {
            set TransRate $expect_out(1,string)
            expect -re $kernel_prompt
            send_log "TransRate $expect_out(1,string)\n"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "cat netperf_tcp_stream\r"
while 1 {
    expect {
        -re "\\\.\[0-9]{2} +(\[0-9]+\\\.\[0-9]{2}) +\r$kernel_prompt" {
            set Throughput $expect_out(1,string)
            expect -re $kernel_prompt
            send_log "Throughput $expect_out(1,string)\n"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send_user "Evaluate performance result.\n"
if { [lindex $argv 1] == "usb" } {
    if { $TransRate > 1900 && $Throughput > 4 } {
        case_pass $case_num
    } else {
        case_fail $case_num
    }
} else {
    if { $TransRate > 1900 && $Throughput > 50 } {
        case_pass $case_num
    } else {
        case_fail $case_num
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
