#!/usr/bin/expect
#
# BFIN CRC driver test
#
# Usage:
#   ./bfincrc_test.exp board_type
#
# Example:
#   ./bfincrc_test.exp BF537-STAMP
#

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
source ../common/kernel_boot.exp

step "Start testing"
set case_num 0

set timeout 10
incr case_num
send "bfin_crc_test -m 0 /dev/bfin-crc0\r"
while 1 {
    expect {
        -nocase -re "(error|fail|No such).*$kernel_prompt" {
            case_fail $case_num
            break
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
            break
        }
    }
}

set timeout 10
incr case_num
send "bfin_crc_test -m 0 /dev/bfin-crc1\r"
while 1 {
    expect {
        -nocase -re "(error|fail|No such).*$kernel_prompt" {
            case_fail $case_num
            break
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
            break
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
