#!/usr/bin/expect
#
# Reserve memory test
#
# Usage:
#   ./reserve_mem_test.exp board_type
#
# Example:
#   ./reserve_mem_test.exp BEAGLE
#

source ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
set bootargs $bootargs_param1
source ../common/kernel_boot.exp

step "Start testing"
set timeout 8
set case_num 0

incr case_num
send "dmesg|head -n 20\r"
while 1 {
    expect {
        -re "Board Memory: ${max_mem}MB.*Kernel Managed Memory: ${res_mem}MB" {
            expect -re $kernel_prompt
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
