#!/usr/bin/expect

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Spawn kermit"
source ../common/spawn_kermit.exp

step "Reboot the kernel."
source ../common/reboot_kernel.exp

sleep 10
set case_num 0

step "Start Sqlite testing"

decide_smp

incr case_num
set timeout 5
send "$smp_prog $smp_flag sqlite3 wishlist.db < /usr/wishlist.sql\r"
expect -re $kernel_prompt

send "$smp_prog $smp_flag sqlite3 wishlist.db \".dump\"\r"
while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        -re "Trace:.*\r\n\r\n" {
            expect -re "$kernel_prompt"
            send_user "\nShow up dump info\n"
            case_fail $case_num
            exit
        }
        timeout {
            case_fail $case_num
        }
    }
}

send "$smp_prog $smp_flag sqlite_test \"foo\"\r"
while 1 {
    expect {
        -re ".*foo <foo@test>.*" {
            case_pass $case_num
                break
        }
        -re "Trace:.*\r\n\r\n" {
            expect -re "$kernel_prompt"
            send_user "\nShow up dump info\n"
            case_fail $case_num
            exit
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass

send_user "Ending $argv0\n"

log_file
