#!/usr/bin/expect

cd $src_root
spawn make
set timeout 1200
set bfin_make_status failure
while 1 {
    expect {
        "\\\(*) \\\[*]" {
            sleep .05
            send "\r"
        }
        -re "rm.*\.fakeroot" { set bfin_make_status success }
        "Error" {set bfin_make_status failure }
        eof { break }
    }
}

if { $bfin_make_status == "failure" } {
    puts "ERROR: Error somewhere during make"
    exit
}
