#!/bin/bash

BOARD_CONFIG=PANDA-STD
BOARD_TYPE=PANDA
ARCH_TYPE=arm
CPU=default
REVISION=default
BINARY_FORMAT=default
ALLOCATOR=slab
ICACHE=default
DCACHE=default
POLICY=default
UART_MODE=default
SMP=on
MPU=default
XENOMAI=off
