#!/usr/bin/expect
#
# lmbench performance test
#
# Usage:
#   ./lmbench_test.exp board_type
#
# Example:
#   ./lmbench_test.exp BF537-STAMP
#

source  ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
source ../common/kernel_boot.exp

step "Start testing"
set case_num 0
set timeout 10
expect -re $kernel_prompt

set timeout 120
incr case_num
send "lat_ctx -s 0 processes 2 8 16\r"
while 1 {
    expect {
        -re "size.* ovr.*16 \[0-9\.]+.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send "lat_ctx -s 16 processes 2 8 16\r"
while 1 {
    expect {
        -re "size.* ovr.*16 \[0-9\.]+.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send "lat_ctx -s 64 processes 2 8 16\r"
while 1 {
    expect {
        -re "size.* ovr.*16 \[0-9\.]+.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
