#!/usr/bin/expect
#
# Test atapi hard disk on target board
#
# Usage:
#   ./atapi_hd_test.exp board_type
#
# Example:
#   ./atapi_hd_test.exp BF548-EZKIT
#

source ../common/kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
# Different bootargs can be set here.
# For example:
# set bootargs $bootargs_param1
source ../common/kernel_boot.exp

set timeout 10
expect -re $kernel_prompt
send "\r"
expect -re $kernel_prompt

step "Start testing"
set case_num 0
set MAX "\r"
set NUM_CYLINDER_DOS "+8G"
set NUM_CYLINDER_EXT2 "+20G"

send "mkdir /mnt/hd1\r"
send "mkdir /mnt/hd2\r"

set timeout 5
incr case_num
send "dmesg | grep ^ata\r"
while 1 {
    expect {
        -re "(TOSHIBA MK4032GAX|FUJITSU MHW2040AT).*78140160 sectors.*configured for UDMA.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "dmesg | grep sd\r"
while 1 {
    expect {
        -re "sda:.*Attached SCSI disk.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "cat /proc/interrupts\r"
while 1 {
    expect {
        -re "pata-bf54x.*$kernel_prompt" {
            send_user "Libata found, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Libata not found, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "cat /proc/devices\r"
while 1 {
    expect {
        -re "sd.*$kernel_prompt" {
            send_user "Libata block device found\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Libata block device not found\n"
            case_fail $case_num
        }
    }
}

set timeout 10
incr case_num
send "fdisk /dev/sda\r"
while 1 {
    expect {
        -re "Command.*:" {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
send -s "p\r"
while 1 {
    expect {
        -re "/dev/sda1.*Command.*:" {
            send -s "d\r"
            expect -re "Partition number.*:"
            send -s "1\r"
            expect -re "Command.*:"
            break
        }
        -re "Command.*:" {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
send -s "p\r"
while 1 {
    expect {
        -re "/dev/sda2.*Command.*:" {
            send -s "d\r"
            expect -re "Selected partition 2.*Command.*:"
            break
        }
        -re "Command.*:" {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
set timeout 20
send -s "w\r"
while 1 {
    expect {
        -re "error" {
            expect -re $kernel_prompt
            case_fail $case_num
        }
        -re "Syncing disks.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        -re "re-read partition table.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 10
send "fdisk /dev/sda\r"
while 1 {
    expect {
        -re "Command.*:" {
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
send -s "n\r"
expect -re "primary.*(partition \\\(1-4\\\))|(Select.*:)"
send -s "p\r"
while 1 {
    expect {
        -re "Partition number.*:" {
            send -s "1\r"
            expect -re "First (cylinder|sector).*:"
            send -s "\r"
            expect -re "Last (cylinder|sector).*:"
            send -s "$NUM_CYLINDER_DOS\r"
            expect -re "Command.*:"
            send -s "t\r"
            expect -re "Hex code.*:"
            send -s "l\r"
            expect -re "Hex code.*:"
            send -s "b\r"
            expect -re "Command.*:"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
send -s "n\r"
expect -re "primary.*(partition \\\(1-4\\\))|(Select.*:)"
send -s "p\r"
while 1 {
    expect {
        -re "Partition number.*:" {
            send -s "2\r"
            expect -re "First (cylinder|sector).*:"
            send -s "\r"
            expect -re "Last (cylinder|sector).*:"
            send -s "$NUM_CYLINDER_EXT2\r"
            expect -re "Command.*:"
            send -s "t\r"
            expect -re "Partition number.*:"
            send -s "2\r"
            expect -re "Hex code.*:"
            send -s "l\r"
            expect -re "Hex code.*:"
            send -s "83\r"
            expect -re "Command.*:"
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}
set timeout 20
send -s "w\r"
while 1 {
    expect {
        -re "error" {
            expect -re $kernel_prompt
            case_fail $case_num
        }
        -re "Syncing disks.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        -re "re-read partition table.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 5
set timeout 300
incr case_num
send "mkdosfs -F 32 /dev/sda1\r"
while 1 {
    expect {
        -re "(Hardware Trace|No such).*$kernel_prompt" {
            send_user "mkdosfs sda1 fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "mkdosfs sda1 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "mkdosfs sda1 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 900
incr case_num
send "mke2fs /dev/sda2\r"
while 1 {
    expect {
        -re "(Hardware Trace|No such).*$kernel_prompt" {
            send_user "mke2fs sda2 fail\n"
            case_fail $case_num
        }
        -re "(Superblock backups stored on blocks:|Writing superblocks).*$kernel_prompt" {
            send_user "mke2fs sda2 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "mke2fs sda2 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "mount /dev/sda1 /mnt/hd1\r"
while 1 {
    expect {
        -re "mount.*failed.*$kernel_prompt" {
            send_user "mount sda1 failed, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "mount sda1 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "mount sda1 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "mount /dev/sda2 /mnt/hd2\r"
while 1 {
    expect {
        -re "mount.*failed.*$kernel_prompt" {
            send_user "mount sda2 failed, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "mount sda2 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "mount sda2 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "cp /bin/busybox /mnt/hd1/abc\r"
expect  -re $kernel_prompt
send "ls /mnt/hd1\r"
while 1 {
    expect {
        -re "abc.*$kernel_prompt" {
            send_user "Copy to HD done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Copy to HD timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "rm /mnt/hd1/abc\r"
expect  -re $kernel_prompt
send "ls /mnt/hd1\r"
while 1 {
    expect {
        -re "abc.*$kernel_prompt" {
            send_user "Delete in HD fail, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "Delete in HD done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Delete in HD timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 60
incr case_num
send "time dd conv=fsync if=/dev/zero of=/mnt/hd1/test.bin bs=1M count=10\r"
while 1 {
    expect {
        -re "records in.*records out.*real.*user.*sys.*$kernel_prompt" {
            send_user "Generate file done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Generate file timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 60
incr case_num
send "time cat /mnt/hd1/test.bin > /dev/null\r"
while 1 {
    expect {
        -re "real.*user.*sys.*$kernel_prompt" {
            send_user "Read file done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Read file timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 60
incr case_num
send "time dd conv=fsync if=/dev/zero of=/mnt/hd2/test.bin bs=1M count=10\r"
while 1 {
    expect {
        -re "records in.*records out.*real.*user.*sys.*$kernel_prompt" {
            send_user "Generate file done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Generate file timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 60
incr case_num
send "time cat /mnt/hd2/test.bin > /dev/null\r"
while 1 {
    expect {
        -re "real.*user.*sys.*$kernel_prompt" {
            send_user "Read file done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "Read file timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "umount /mnt/hd1\r"
while 1 {
    expect {
        -re "umount.*failed.*$kernel_prompt" {
            send_user "umount sda1 failed, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "umount sda1 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "umount sda1 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "umount /mnt/hd2\r"
while 1 {
    expect {
        -re "umount.*failed.*$kernel_prompt" {
            send_user "umount sda2 failed, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "umount sda2 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "umount sda2 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

step "Start bonnie++ test"

set timeout 900
incr case_num
send "mke2fs /dev/sda2\r"
while 1 {
    expect {
        -re "Hardware Trace.*$kernel_prompt" {
            send_user "mke2fs sda2 crash, test fail\n"
            case_fail $case_num
        }
        -re "(Superblock backups stored on blocks:|Writing superblocks).*$kernel_prompt" {
            send_user "mke2fs sda2 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "mke2fs sda2 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "mount /dev/sda2 /mnt/hd2\r"
while 1 {
    expect {
        -re "mount.*failed.*$kernel_prompt" {
            send_user "mount sda2 failed, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "mount sda2 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "mount sda2 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

set timeout 3600
incr case_num
send "time bonnie++ -u root -d /mnt/hd2 -s 200M\r"
while 1 {
    expect {
        -re "Hardware Trace" {
            set timeout 30
            expect -re $kernel_prompt
            send_user "bonnie++ failed\n"
            case_fail $case_num
        }
        -re "Latency.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            send_user "bonnie++ timeout\n"
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "umount /mnt/hd2\r"
while 1 {
    expect {
        -re "umount.*failed.*$kernel_prompt" {
            send_user "umount sda2 failed, test fail\n"
            case_fail $case_num
        }
        -re $kernel_prompt {
            send_user "umount sda2 done, test pass\n"
            case_pass $case_num
            break
        }
        timeout {
            send_user "umount sda2 timeout, test fail\n"
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
