#!/usr/bin/expect
#
# touchscreen test
#
# Usage:
#   ./touchscreen_test.exp board_type
#
# Example:
#   ./touchscreen_test.exp BF537-STAMP
#

source ../common/kernel_config.exp

set screen_name "7877"
if { $argc >= 2} {
    set screen_name [lindex $argv 1]
}

log_file [log_file_name $argv0.$screen_name ]

source ../common/board_info.exp
send_user "Starting $argv0\n"

if { $screen_name == "7877" || $screen_name == "7879" } {
    send_log "\n#### Board name is $screen_name.\n"
} else {
    send_log "\n#### This config $screen_name is not supported. Sorry.\n"
    exit
}

set TITLE [title "$argv0"]
append TITLE " ($screen_name)"

step "Start kermit"
source ../common/spawn_kermit.exp

step "Boot kernel"
source ../common/kernel_boot.exp

step "Start testing"
sleep 4
set case_num 0

set timeout 10
incr case_num
send -s "event_test /dev/input/event0\r"
while 1 {
    expect {
        -re "Input device name.* Touchscreen.*Testing.*exit" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

puts "\nPlease touch the keypad...\n"
incr case_num
while 1 {
    expect {
        -re "Event: time.*type.*code.*value" {
            sleep 1
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 5
incr case_num
send -s "\3"
while 1 {
    expect {
         -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
